package com.bfchengnuo.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-07-06T11:02:05.718+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://service.bfchengnuo.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://service.bfchengnuo.com/", className = "com.bfchengnuo.client.service.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://service.bfchengnuo.com/", className = "com.bfchengnuo.client.service.CheckUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean checkUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.bfchengnuo.client.service.User arg0
    );
}
